project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Jianxiang Tan"
  site-url: https://jianxiang.github.io
  favicon: images/site.png
  repo-url: https://github.com/Jianxiang-Tan/jianxiang.github.io
    
  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Conferences"
        href: conferences.qmd
      - text: "Activities"
        href: activity.qmd
      # Removed empty/commented navbar items that produced null entries

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细
