project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Jianxiang Tan"
  site-url: https://jianxiang.github.io
  favicon: images/site-logo.png
  repo-url: https://github.com/Jianxiang-Tan/jianxiang.github.io

  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Conferences"
        href: conferences.qmd
      - text: "Activities"
        href: activities.qmd

format:
  html:
    theme: styles.scss
    toc: true
    toc-position: right
    toc-depth: 3
